libs =
#import libs += libhello%lib{hello}

exe{genuuid}: {hxx ixx txx cxx}{**} $libs testscript

if ($cxx.target.class == 'linux')
  cxx.libs += -luuid
elif ($cxx.target.class == 'windows')
  cxx.libs += ($cxx.target.system == 'mingw32' ? -lrpcrt4 : rpcrt4.lib)

cxx.poptions =+ "-I$out_root" "-I$src_root"
